# Generated by Django 4.2.5 on 2024-09-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_music', models.FileField(upload_to='Music/')),
                ('fav_quote', models.CharField(max_length=500)),
                ('fav_video', models.FileField(upload_to='Video/')),
                ('fav_book', models.CharField(max_length=500)),
            ],
        ),
    ]
