# Generated by Django 5.1 on 2024-09-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_about_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='desc',
            field=models.CharField(max_length=500),
        ),
    ]
