# Generated by Django 5.1 on 2024-09-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=50)),
                ('name2', models.CharField(max_length=50)),
                ('name3', models.CharField(max_length=50)),
                ('name4', models.CharField(max_length=50)),
                ('name5', models.CharField(max_length=50)),
            ],
        ),
    ]
