# Generated by Django 5.1 on 2024-09-29 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
            },
        ),
        migrations.RemoveField(
            model_name='skills',
            name='name1',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='name2',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='name3',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='name4',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='name5',
        ),
        migrations.AddField(
            model_name='skills',
            name='skill_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='skills',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='skills.category'),
        ),
    ]
