# Generated by Django 4.2.5 on 2024-09-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project1', models.CharField(max_length=50)),
                ('project2', models.CharField(max_length=50)),
                ('project3', models.CharField(max_length=50)),
                ('project4', models.CharField(max_length=50)),
                ('project5', models.CharField(max_length=50)),
            ],
        ),
    ]
