# Generated by Django 4.2.5 on 2024-09-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project1',
            field=models.ImageField(null=True, upload_to='Picture/'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project2',
            field=models.ImageField(null=True, upload_to='Picture/'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project3',
            field=models.ImageField(null=True, upload_to='Picture/'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project4',
            field=models.ImageField(null=True, upload_to='Picture/'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project5',
            field=models.ImageField(null=True, upload_to='Picture/'),
        ),
    ]
