# Generated by Django 5.1 on 2024-09-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Social',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='text',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='update',
        ),
        migrations.AddField(
            model_name='banner',
            name='description',
            field=models.TextField(default='No description provided'),
        ),
        migrations.AddField(
            model_name='banner',
            name='facebook_link',
            field=models.URLField(default='https://facebook.com/'),
        ),
        migrations.AddField(
            model_name='banner',
            name='github_link',
            field=models.URLField(default='https://github.com/'),
        ),
        migrations.AddField(
            model_name='banner',
            name='instagram_link',
            field=models.URLField(default='https://instagram.com/'),
        ),
        migrations.AddField(
            model_name='banner',
            name='linkedin_link',
            field=models.URLField(default='https://linkedin.com/'),
        ),
        migrations.AddField(
            model_name='banner',
            name='welcome_text',
            field=models.CharField(default='Welcome', max_length=255),
        ),
    ]
