# Generated by Django 4.2.5 on 2024-09-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('github_link', models.URLField(default='https://github.com/')),
                ('linkedin_link', models.URLField(default='https://linkedin.com/')),
                ('instagram_link', models.URLField(default='https://instagram.com/')),
                ('facebook_link', models.URLField(default='https://facebook.com/')),
            ],
        ),
    ]
